### ISSUE TITLE
Chọn đề tài, Đặt tên nhóm, Chọn nhóm trưởng

### ISSUE THREAD

**Issue by badungphan99** [badungphan99/SE03-Group03#1]
# Issues đầu tiên của nhóm: Chọn đề tài, đặt tên nhóm, chọn nhóm trưởng
Mọi người cứ commnet trực tiếp vào luôn cho tiện cũng được
##  Đề tài
Thời gian dự kiến hoàn thành là khoảng 2 tháng nên đừng ham hố chọn cái trâu bò quá lại không kịp.
## Tên nhóm
Tên gì cũng được miễn là nghe vui vui và ngắn gọn.
## Nhóm trưởng
Khuyến kích là người từng có kinh nghiệm tham gia các agile/scrum  Tuy nhiên không phải điều kiện gì hết ai thích làm thì ứng cử thôi.
`Cứ ý kiến nhiệt tình vào nhá :))`

**Comment by hoangi19** [comment]
Đề tài theo mình có thể làm theo chủ đề phát triển phần mềm quản lý. Ví dụ : quản lý bãi gửi xe.
Ngôn ngữ và công nghệ thì có thể dùng C/C++ hoặc Java để làm do nhóm mình đều học Java và C/C++ nên có thể dễ làm việc và dễ phát triển thêm các tính năng. 
Nhóm trưởng thì mình đề cử Dũng vì Dũng có kinh nghiệm làm Leader và làm dự án.

**Comment by kim-cuc** [comment]
Theo mình, dự án có thể làm phần mềm hoặc trang web quản lý. Một số đề tài mình đề xuất như sau:
+ Quản lý giảng đường
+ Quản lý thư viện
+ Quản lý điểm sinh viên/ đăng kí môn học

Về nhóm trưởng mình cũng đề cử bạn Dũng vì bạn đã có nhiều kinh nghiệm thực tế khi làm dự án

**Comment by badungphan99** [comment]
@hoangi19 @kimcucnguyen Làm các ứng dụng quản lý được đấy @HanhPhamHus có ý kiến khác không ?
Nếu mà làm về quản lý thì còn phải cả chọn cơ sở dữ liệu nhỉ. Dùng luôn mysql được không ?

**Comment by hanhpham99** [comment]
halo t thấy làm quản lý được đso

**Comment by hanhpham99** [comment]
nhưng sợ có nhiều nhóm í, có sợ cạnh tranh nhiều k

**Comment by badungphan99** [comment]
# Kết quả lịch họp 09/10/2019
- Thống nhất về đề tài: Xây dựng trang web học tập 
- Tên nhóm: mai chốt
- Phân chia công việc các thành viên:
    - @badungphan99 Scrum master
    - @HanhPhamHus làm phần front-end cho trang web
    - @kimcucnguyen @hoangi19 @badungphan99  sẽ xử lý phần back-end
