### ISSUE TITLE
Không tạo được user mới

### ISSUE THREAD

**Issue by badungphan99** [badungphan99/SE03-Group03#12]
Khi tạo 1 user mới theo liên kết khóa thì cần có type account, tuy nhiên trên giao diện cũng như trong phần user init đều không yêu cầu

**Comment by kim-cuc** [comment]
Cách để tạo user mới với khóa ngoại ở bảng type_account đây nhé:

    teacherAccount = TypeAccount('Teacher')
    studentAccount = TypeAccount('Student')

    db.session.add(teacherAccount)
    db.session.add(studentAccount)

    user1 = User('Toan', '123', 'NguyenVanToan', 'toan@gmail.com')
    teacherAccount.users.append(user1)

    db.session.add(user1)
    db.session.commit()

**Comment by badungphan99** [comment]
Vậy mình có cần sửa từ giao diện không ? ý là chọn type account ấy ?

**Comment by hanhpham99** [comment]
t mới làm cái check thử acc login bằng js , mn vô xem nhé.
có 3 acc thử là giaovien, hocvien và admin. pass của cả 3 acc là 123456789.

**Comment by badungphan99** [comment]
Ơ c có sửa gì không @kimcucnguyen hôm nay tự nhiên lại insert vào mà không cần type account

**Comment by badungphan99** [comment]
@HanhPhamHus cần bổ sung thêm fullname, highest_degree , university , major nhưng chỉ yêu cầu một số thông tin là bắt buộc điền username, pass, fullname, email. Phần kiểm tra các thông tin bị thiếu hay trống @hoangi19 đã làm xong rồi, Hạnh chỉ cần thêm vào ở giao diện thôi nhé.
