### ISSUE TITLE
Use case 1: Login

### ISSUE THREAD

**Issue by kim-cuc** [badungphan99/SE03-Group03#13]
Mô tả: 

Người dùng điền username, password, sau đó click button Login 
Hệ thống kiểm tra trong cơ sở dữ liệu có tồn tại tài khoản với username và password tương ứng hay không.
- Nếu có: Chuyển đến trang các khóa học 
- Nếu không: Hiện thông báo không tìm thấy

**Comment by hoangi19** [comment]
https://pythonise.com/series/learning-flask/flask-message-flashing
t đang thử cách dùng flask-flashing để gửi mess từ sever lên giao diện

**Comment by hoangi19** [comment]
https://code-maven.com/slides/python-programming/flask-login

**Comment by hoangi19** [comment]
https://flask-login.readthedocs.io/en/latest/#flask_login.LoginManager
