### ISSUE TITLE
Lưu trữ tài liệu về các khóa học

### ISSUE THREAD

**Issue by badungphan99** [badungphan99/SE03-Group03#14]
Lưu trữ tài liệu của các khóa học ở đâu, hình thức upload như thế nào ?

**Comment by hoangi19** [comment]
t đang xem thử các dùng này https://www.programcreek.com/python/example/51528/flask.request.files

**Comment by hoangi19** [comment]
https://flask.palletsprojects.com/en/1.1.x/patterns/fileuploads/

**Comment by hoangi19** [comment]
đã update bản test cho upload file các định dạng ['txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif']. cần sửa thêm giao diện và config lại UPLOAD_FOLDER
