### ISSUE TITLE
Phần register hiện thông báo chưa đúng, không nhập username vẫn tạo tài khoản được

### ISSUE THREAD

**Issue by kim-cuc** [badungphan99/SE03-Group03#15]
Phần register hiện thông báo chưa đúng:
- Khi để trống tất cả các phần và click register thì hiện thông báo "Mật khẩu phải trên 8 kí tự " ?

Không nhập username vẫn tạo tài khoản được:
- Ở đây chỉ cần nhập email và mật khẩu đã hiện thông báo tạo tài khoản thành công
- Tuy nhiên trang login chỉ có yêu cầu nhập username và password ?

**Comment by kim-cuc** [comment]
Trong phần register, cần hiển thị những phần nào là bắt buộc nhập để có thể tạo được một tài khoản mới nữa

**Comment by hoangi19** [comment]
> Phần register hiện thông báo chưa đúng:
> 
> * Khi để trống tất cả các phần và click register thì hiện thông báo "Mật khẩu phải trên 8 kí tự " ?
> 
> Không nhập username vẫn tạo tài khoản được:
> 
> * Ở đây chỉ cần nhập email và mật khẩu đã hiện thông báo tạo tài khoản thành công
> * Tuy nhiên trang login chỉ có yêu cầu nhập username và password ?

t đã fix phần thông báo username, password, email, fullname rỗng

**Comment by hoangi19** [comment]
> Trong phần register, cần hiển thị những phần nào là bắt buộc nhập để có thể tạo được một tài khoản mới nữa

@HanhPhamHus hạnh ơi sửa hộ phần giao diện

**Comment by hanhpham99** [comment]
giao diện đã sửa
