### ISSUE TITLE
Tạo thêm bảng trong csdl

### ISSUE THREAD

**Issue by hoangi19** [badungphan99/SE03-Group03#16]
@kimcucnguyen  tớ đang cần thêm 1 bảng lưu lại id người upload ảnh/tài liệu lên sever và đường dẫn đến ảnh/tài liệu đấy trên sever và tên file gốc

| user_id | filename_upload | path_in_sever |
|---------|:-------------------:|-------------:|

**Comment by badungphan99** [comment]
|Course_ID|File name upload|path save file| file type|
|----------|:----------------:|:------------:|--------:|

T nghĩ là cần thêm 1 bảng nữa như thế này file type sẽ có 2 loại:
- banner của course
- document trong course đấy 

Cúc xem qua có hợp lý không nhé

**Comment by hoangi19** [comment]
> @kimcucnguyen tớ đang cần thêm 1 bảng lưu lại id người upload ảnh/tài liệu lên sever và đường dẫn đến ảnh/tài liệu đấy trên sever và tên file gốc
> | user_id | filename_upload | path_in_sever |
> |---------|:-------------------:|----------------:|

**Comment by kim-cuc** [comment]
T thấy cần có cột để ghi vị trí file nữa, ví dụ file ở trong 1 course nhưng nó là của chung cả course (ảnh minh họa, quảng cáo) hay nằm ở section nào của course thì cần có cách đánh dấu lại, tương tự với forum và post nữa

**Comment by kim-cuc** [comment]
Của @hoangi19 và @badungphan99 t gộp lại được ko? Vì khi người dùng tạo một khóa học mới thì ảnh minh họa, quảng cáo hay tài liệu cũng do người dùng upload lên mà? Thế thì cũng cần xác định user_id ở bảng file_upload nữa

**Comment by kim-cuc** [comment]
@badungphan99 và @hoangi19 ơi, t đã tạo thêm các bảng file_upload, file_location, file_type trong csdl để người dùng upload file nhé
