### ISSUE TITLE
Lấy danh sách tên giáo viên phụ trách khóa học

### ISSUE THREAD

**Issue by kim-cuc** [badungphan99/SE03-Group03#22]
- Thêm dữ liệu vào bảng teacher_course
- Lấy danh sách các giáo viên giảng dạy một khóa học cho trước

**Comment by kim-cuc** [comment]
Thêm dữ liệu vào bảng user, course:

    teacherAccount = TypeAccount('Teacher')
    studentAccount = TypeAccount('Student')

    db.session.add_all([teacherAccount, studentAccount])

    user1 = User('Toan', '123', 'Nguyễn Văn Toản', 'toan@gmail.com')
    user2 = User('Thuy', '345', 'Nguyễn Thị Thủy', 'thuynt@gmail.com')
    user3 = User('Van', '654', 'Trần Hải Vân', 'vanth@gmail.com')

    teacherAccount.users.append(user1)
    teacherAccount.users.append(user2)
    teacherAccount.users.append(user3)

    course1 = Course("Tổng ôn Vật Lý 10-11-12", "Mô tả: Ôn thi đại học môn Vật Lý", 120)
    course2 = Course("Giải tích", "Mô tả: Các kiến thức cơ bản về Giải tích", 220)

    db.session.add_all([user1, user2, user3, course1, course2])

**Comment by kim-cuc** [comment]
Thêm dữ liệu vào bảng teacher_course

    teacherCourse1 = TeacherCourse()
    teacherCourse1.course = course1
    user1.courses.append(teacherCourse1)

    teacherCourse2 = TeacherCourse()
    teacherCourse2.course=course1
    user2.courses.append(teacherCourse2)

    db.session.commit()

=> Khóa học "Tổng ôn Vật Lý 10-11-12" có 2 giáo viên là Nguyễn Văn Toản và Nguyễn Thị Thuỷ

**Comment by kim-cuc** [comment]
Lấy ra danh sách giáo viên giảng dạy một khóa học khi biết mã số của khóa học:
    
    courseId = 1
    userTeacher = db.session.query(User.fullname).join(TeacherCourse).join(Course).filter(Course.id == courseId).all()

    for name in userTeacher:
        print(name)

**Comment by kim-cuc** [comment]
Kết quả sau khi in:
('Nguyễn Văn Toản',)
('Nguyễn Thị Thủy',)

**Comment by kim-cuc** [comment]
@hoangi19 cách làm đây nhé

**Comment by hoangi19** [comment]
t đã sửa trong commit 3bcaf6e để thêm tên giáo viên lúc hiển thị trên block_home
