### ISSUE TITLE
Các mục của lesson

### ISSUE THREAD

**Issue by hoangi19** [badungphan99/SE03-Group03#26]
Lesson hiện tại chưa có gì. Cần thêm các thông tin liên quan để hiển thị lesson

**Comment by hanhpham99** [comment]
các thông tin liên quan gồm: 
-Tên bài
-Nội dung của bài học (document , có thể là các clip, hình ảnh..)
-Tên tác giả
-Ngày đăng

**Comment by hoangi19** [comment]
@kimcucnguyen

**Comment by kim-cuc** [comment]
> các thông tin liên quan gồm:
> -Tên bài
> -Nội dung của bài học (document , có thể là các clip, hình ảnh..)
> -Tên tác giả
> -Ngày đăng

@HanhPhamHus ơi, giao diện khi click vào lesson chưa có theo các phần trên nhé
