### ISSUE TITLE
Các tính năng cơ bản của chương trình

### ISSUE THREAD

**Issue by badungphan99** [badungphan99/SE03-Group03#3]
# Các tính năng cơ bản của chương trình 

Trong phiên bản đầu tiên sẽ cần có một số chức năng chính, quan trọng trước sau đấy sẽ update dần, dư kiến sẽ hoàn thành trong 3 tuần - 1 tháng cũng đồng thời là Sprint đầu tiên của project luôn.

**Comment by hanhpham99** [comment]
- Xây dựng chương trình thành các lớp học tập online gồm 2 loại (có phí và miễn phí ).
- Có chia sẻ tài liệu, giáo trình ở đầu các lớp học .
- Mỗi lớp học có các video bài giảng theo lộ trình .
- Có chức năng comment dưới từng bài giảng để học viên đặt câu hỏi. câu hỏi đó sẽ được admin chuyển trực tiếp cho giáo viên của video đó để trả lời .
- có các bài kiểm tra năng lực sau một số bài học.

**Comment by hoangi19** [comment]
Chúng ta có thể tham khảo 1 số trang web với định hướng tương tự như codelearn.io.
Chia sẻ tài liệu thì t thấy có thể xây dựng theo dạng viết blog. Blog sẽ có cả của giáo viên và sinh viên làm tăng tài liệu và giao tiếp giữa giáo viên / sinh viên lẫn nhau. 1 blog cũng có thể được đánh giá tốt hay không và có góp ý xây dựng.

**Comment by kim-cuc** [comment]
### Người dùng
- Giáo viên: cần xác minh danh tính, được tạo hoặc tham gia dạy các khóa học, đăng bài học trong những khóa học đã tạo hoặc tham gia
- Học sinh, sinh viên và những người khác được đăng kí học các khóa học. Đối với học sinh, sinh viên sau khi xác minh danh tính sẽ có nhiều ưu tiên hơn
- Admin: người kiểm soát việc xác minh danh tính của các tài khoản, kiểm duyệt các khóa học được tạo, các bài học, bài đăng, comment trong diễn đàn. Nếu phát hiện trường hợp vi phạm thì xóa bài và vô hiệu hóa tài khoản
### Khóa học
- Gồm tiêu đề, thể loại, mô tả, ngày tạo, thời lượng, giáo viên, số lượng người đăng kí học, các bài học 
- Cuối mỗi bài học có phần quiz, nguời học làm bài và được chấm điểm, người học có thể xem lại điểm của từng bài quiz và điểm cả khóa học
- Sau khi xem tất cả các bài học và làm hết các bài quiz đạt ngưỡng điểm yêu cầu, người học được tính là đã hoàn thành khóa học
- Mỗi khóa học có một diễn đàn riêng để trao đổi, trong diễn đàn đó những người tham gia khóa học có thể đăng bài, xem, comment, like bài viết và like comment
### Bài viết
- Gồm tiêu đề, thể loại, ngày viết, nội dung, có phần comment, like
- Mọi người đã đăng kí tài khoản đều có thể tạo bài viết riêng để chia sẻ kiến thức. 
- Bài viết sau khi được Admin kiểm duyệt và đạt yêu cầu sẽ được đăng vào mục blog để tất cả mọi người có thể xem được
