### ISSUE TITLE
Các công nghệ sử dụng

### ISSUE THREAD

**Issue by kim-cuc** [badungphan99/SE03-Group03#4]

**Comment by badungphan99** [comment]
Một số ý kiến của t như sau
- Phần cơ sở dữ liệu: sử dụng mysql làm db chính để lưu trữ và có thể kết hợp thêm elastic search cho một số việc như lưu trữ thông tin hành vi khách hàng, search tài liệu đang có
- Code back-end có hai lựa chọn hoặc là dùng cpp cơ mà code sẽ hơi cồng kềnh hơn tí hoặc là dùng python3 flask thì tiện hơn nhanh hơn
- Phần front-end không biết @HanhPhamHus  quen với việc dùng ngôn ngữ hay frame work gì nhỉ?
- Công cụ quản lý phiên bản code dùng luôn git :))
- Mô hình nhóm sẽ tổ chức theo dạng scrum team

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hanhpham99** [comment]
font-end t sẽ dùng html/css bootstrap js nhé.

**Comment by kim-cuc** [comment]
Phần back-end t chọn dùng python3 flask nhé
