### ISSUE TITLE
Thiết kế cơ sở dữ liệu

### ISSUE THREAD

**Issue by kim-cuc** [badungphan99/SE03-Group03#5]
Tạo cơ sở dữ liệu
- Xác định các bảng, thuộc tính, kiểu dữ liệu, mối quan hệ, khóa chính, khóa ngoại, các ràng buộc cần thiết

**Comment by kim-cuc** [comment]
### Mô tả yêu cầu về cơ sở dữ liệu
#### 1. Tài khoản đăng nhập
- Gồm các thông tin: mã số, tên đăng nhập, mật khẩu, email, tên đầy đủ, hình đại diện, chuyên ngành, học vấn, tên trường, công việc, quốc gia, ngày tạo tài khoản, thể loại tài khoản, trạng thái xác minh danh tính, trạng thái hoạt động. 
- Admin có các thông tin như tài khoản thường
- Với tài khoản giáo viên có thể tạo và tham gia dạy nhiều khóa học hoặc không tham gia khóa học nào.
- Các tài khoản còn lại có thể đăng kí học nhiều khóa học hoặc không học khóa nào

#### 2. Khóa học
- Gồm: mã số, tiêu đề, thể loại, mô tả, ngày tạo, giáo viên, người học, các bài học và một diễn đàn để thảo luận
- Một khóa học có thể được giảng dạy bởi nhiều giáo viên, được nhiều người học
- Mỗi bài học gồm tiêu đề, nội dung, có thể có phần câu hỏi trắc nghiệm hoặc không.
- Phần câu hỏi trắc nghiệm: Có tiêu đề, nội dung, đáp án, điểm số
- Diễn đàn gồm bài viết, bình luận
- Thông tin người học: có phần điểm toàn bộ khóa hoc

#### 3. Bài viết: 
- Gồm mã số, tiêu đề, thể loại, nội dung, ngày tạo, trạng thái hoạt động, bình luận, lượt like
- Bài viết có thể ở mục diễn đàn thảo luận trong khóa học hoặc không thuộc khóa học nào (ở mục blog)
- Bình luận: gồm nội dung, ngày tạo
- Like: người dùng có thể chọn like bài viết, like bình luận

**Comment by kim-cuc** [comment]
#### Sơ đồ mối quan hệ giữa các bảng trong cơ sở dữ liệu
https://drive.google.com/file/d/1CRA23Htkwn7iirtaNs5WBNXk40t-7y19/view

**Comment by kim-cuc** [comment]
Tớ mới vẽ thử các bảng trong cơ sở dữ liệu và mối quan hệ của chúng ở trên, các cậu xem có gì cần sửa hay không nhé

**Comment by badungphan99** [comment]
Các trường thông tin của một user thì chỉ bắt buộc một số cái thôi nhỉ. Sản phẩm của mình là trợ giúp cho việc học tập ở lớp chứ không phải là thay thế nên một số trường thông tin như tên trường, học vấn, chuyên ngành có thể có hoặc không.

**Comment by hanhpham99** [comment]
T thấy user có nhiều thông tin cần thiết quá. T nghĩ có lẽ không cần nhiều đến vậy.
