### ISSUE TITLE
Tìm hiểu Flask, SQLAlchemy

### ISSUE THREAD

**Issue by kim-cuc** [badungphan99/SE03-Group03#6]
- Cách cài đặt, sử dụng Flask, SQLAlchemy

**Comment by hoangi19** [comment]
1 số tài liệu
https://towardsdatascience.com/sqlalchemy-python-tutorial-79a577141a91
https://viblo.asia/p/gioi-thieu-sqlalchemy-trong-pythonpart-1-Q7eERE9rRgNj
https://docs.sqlalchemy.org/en/13/
https://code.tutsplus.com/vi/tutorials/building-restful-apis-with-flask-an-orm-with-sqlalchemy--cms-26706
