### ISSUE TITLE
Tìm hiểu cách tổ chức các folder, file trong project

### ISSUE THREAD

**Issue by kim-cuc** [badungphan99/SE03-Group03#8]
Tìm hiểu cách tổ chức các folder, file khi code bằng Python và sử dụng Flask, SQLAlchemy

**Comment by badungphan99** [comment]
Có một file requirements.txt ở ngoài cùng để khi clone về chỉ cần gõ một lệnh là các thư viện mình dùng sẽ được kéo về đầy đủ
Một thư mục  config để có thể viết các file config như tạo db, hay update một số thứ khác,..
Một thư mục chứa phần code back end.
Một thư mục chứa phần code front end.
